<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

use Drupal\Core\Link;
use Drupal\Core\Render\Element;
use Drupal\Core\Form\FormStateInterface;

function commerce_multivendor_form_alter(&$form, &$form_state, $form_id){
  
    //customize product entry.
    if ($form_id == 'commerce_product_default_add_form') {
        
        $uid = \Drupal::currentUser()->id();
        
        $entities = \Drupal::entityTypeManager()->getStorage('commerce_store_locations')->loadByProperties(['uid' => $uid]);
        
        if (empty($entities)) {
            
            $link = Link::createFromRoute('Add a new store.', 'entity.commerce_multivendor.add_form');
            
            $form['warning'] = [
                '#markup' => t("Products can't be created until a store has been added. @link", ['@link' => $link->toString()]),
                '#weight' => -50
            ];
            
            $form['actions']['submit']['#access'] = false;
            $form['actions']['submit_continue']['#access'] = false;
        }
        
        $form['#submit'][] = 'commerce_multivendor_product_form_submit';
        $form['actions']['submit']['#submit'][] = 'commerce_multivendor_product_form_submit';
    }
    
}

/**
 * Redirect 
 */
function commerce_multivendor_product_form_submit(array &$form, FormStateInterface $form_state) {
    $url = '/seller/dashboard';
    
    return new \Symfony\Component\HttpFoundation\RedirectResponse($url);
}